BUGFIX: Add missing installed files to specfile
There are two new files installed, but not packaged to rpm. Let's add it
into specfile.

Fix for rpmbuild error
error: Installed (but unpackaged) file(s) found:
    /opt/gdc/zuul/share/doc/jwcrypto/LICENSE
    /opt/gdc/zuul/share/doc/jwcrypto/README.md